# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2024-04-17T15:35:37+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Course(BaseModel):
    id: str
    numsections: int
    sectionlist: List[str]
    editmode: bool
    highlighted: str
    maxsections: str
    baseurl: str
    statekey: str


class SectionItem(BaseModel):
    id: str
    section: int
    number: int
    title: str
    hassummary: bool
    rawtitle: None
    cmlist: List[str]
    visible: bool
    sectionurl: str
    current: bool
    indexcollapsed: bool
    contentcollapsed: bool
    hasrestrictions: bool


class CmItem(BaseModel):
    id: str
    anchor: str
    name: str
    visible: bool
    sectionid: str
    sectionnumber: int
    uservisible: bool
    hascmrestrictions: bool
    accessvisible: bool
    url: str
    istrackeduser: bool
    completionstate: Optional[int] = None


class Model(BaseModel):
    course: Course
    section: List[SectionItem]
    cm: List[CmItem]
